# Generated by Django 3.2.4 on 2021-06-21 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Created'), ('A', 'Accepted'), ('S', 'Sent'), ('D', 'Delivered'), ('L', 'Closed'), ('X', 'Cancelled')], max_length=1)),
                ('create_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Order Statuses',
                'ordering': ('-order_id', '-create_timestamp'),
                'unique_together': {('order', 'status')},
            },
        ),
    ]
